packages:
  - packages/*

catalogs:
  build:
    vite: ^7.1.9
    vite-plugin-dts: ^4.5.4
  dev:
    eslint: ^9.37.0
    prettier: ^3.6.2
    typescript: ^5.9.3
    vitest: ^3.2.4
  types:
    '@types/node': ^24.7.0

minimumReleaseAge: 10080
