packages:
  - 'packages/*'

# number of minutes that must pass after a version is published before pnpm will install it
# 1 week = 60*24*7 = 10080
minimumReleaseAge: 10080

catalogs:
  dev:
    'eslint': '^9.36.0'
    'prettier': '^3.6.2'
    'typescript': '^5.9.2'
    'vitest': '^3.2.4'

  build:
    'vite': '^7.1.5'
    'vite-plugin-dts': '^4.5.4'

  types:
    '@types/node': '^24.5.1'
