packages:
  - packages/*

catalogs:
  build:
    vite: ^7.1.6
    vite-plugin-dts: ^4.5.4
  dev:
    eslint: ^9.36.0
    prettier: ^3.6.2
    typescript: ^5.9.2
    vitest: ^3.2.4
  types:
    '@types/node': ^24.5.2

minimumReleaseAge: 10080
