packages:
  - packages/*

catalogs:
  build:
    vite: 7.3.1
    vite-plugin-dts: 4.5.4
  dev:
    eslint: 9.39.2
    prettier: 3.8.1
    typescript: 5.9.3
    vitest: 4.0.18
  types:
    '@types/node': 25.2.0

minimumReleaseAge: 4320
