packages:
  - packages/*

catalogs:
  build:
    vite: ^7.1.12
    vite-plugin-dts: ^4.5.4
  dev:
    eslint: ^9.38.0
    prettier: ^3.6.2
    typescript: ^5.9.3
    vitest: ^4.0.5
  types:
    '@types/node': ^24.9.2

minimumReleaseAge: 4320
